/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.1/samples
 */
plugins {
  kotlin("jvm") version "1.6.0"
}

repositories {
  mavenCentral()
}

tasks {
  sourceSets {
    main {
      java.srcDirs("src")
    }
  }

  wrapper {
    gradleVersion = "7.3"
  }
}
